### PR TITLE
Re-export hyper::server::Request

### PR DESCRIPTION
**Pull request by faern**
Re-export `hyper::server::Request` in `jsonrpc_http_server` so that any user of this library who wants to write a middleware or meta extractor does not have to explicitly depend on and import hyper by themselves. Will make it easier to use.

### CODE REVIEW

**Comment by tomusdrw** [comment]
Shouldn't we re-export `Response` as well for completeness? Or maybe it would be better to re-export whole hyper?

**Comment by faern** [comment]
I didn't notice `hyper::server::Response` was used publicly. But it is. So yes, it should be re-exported. But it collides with the local `Response`, so one of them must change name.

I think re-exporting all of hyper is overkill, one does not need the rest in order to interact with this library.

**Comment by faern** [comment]
Could be `pub use hyper::server::{Request as HyperRequest, Reply as HyperReply};` or do you prefer just re-exporting all of hyper?

**Comment by tomusdrw** [comment]
I'd go with re-exporting all of hyper, cause if you for instance want to check a header on request you will need it anyway, same with creating a response.

**Comment by faern** [comment]
Oh wait.. Hyper already is publicly exported here. My bad! This PR is void :)

**Pull request closed without merging**
