### PR TITLE
Ws CloseHandle for closing while waiting

### PR DESCRIPTION
**Pull request by faern**
Solves #148

### CODE REVIEW

**Comment by faern** [comment]
If someone knows a way to do this without a mutex that would of course be nicer, but this works.

**Comment by tomusdrw** [comment]
You could try to make `server-utils::reactor::Remote` cloneable and  move the `Mutex` there, cause it's only required if the event loop has actually been spawned.

**Comment by faern** [comment]
@tomusdrw I looked into moving the locking now. However, I think it made things less clear/nice. The variant would become `Spawned(Arc<Mutex<Option<RpcEventLoop>>>)`. The option is there since `RpcEventLoop::close` and `wait` consumes self, so I must take the ownership of it. And it resulted in having to lock the lock in all three methods on `Remote`.

The current solution put the lock higher up, but the only actual place where it's locked is in `CloseHandle::close`. So there is no locking performance penalty (except the `Arc` decrement) unless someone actually use the `CloseHandle`, and since closing is a one time operation it should not be that crucial.

**Comment by faern** [comment]
Ping? :)

**Comment by tomusdrw** [comment]
Thanks!

**Pull request merged**
