### PR TITLE
Update log to 0.4 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by kirushik** [comment]
@debris I've updated this PR to make it mergeable again; please re-review.

**Comment by Eijebong** [comment]
Oh it wasn't mergeable anymore ? Sorry, you don't get notifications when that happens :/

**Comment by Eijebong** [comment]
So i bumped the version but it was never released. Is there a way to publish it now ? :)

**Comment by tomusdrw** [comment]
@Eijebong done:)

**Pull request merged**
