### PR TITLE
Bump version.

### PR DESCRIPTION
**Pull request by tomusdrw**
Related #607

### CODE REVIEW

**Review by niklasad1 — APPROVED** [review]
LGTM

**Review by dvdplm — APPROVED** [review]

**Review by Xanewok — COMMENTED** [review]
Looks good, thanks! Do we want to address https://github.com/paritytech/jsonrpc/issues/605 as well before cutting the new release?

**Comment by tomusdrw** [comment]
> Looks good, thanks! Do we want to address #605 as well before cutting the new release?

@Xanewok your call. IMHO better to do it separately, and see if we run into any regressions without soketto, perhaps #605 could be implemented without an API change so it would be transparent to the users.

**Comment by Xanewok** [comment]
@tomusdrw Makes sense, let's do that separately. Deploy away! :rocket:

**Review by Xanewok — APPROVED** [review]

**Pull request merged**
