### PR TITLE
Optional TLS support for HTTP transport (#433)

### PR DESCRIPTION
**Pull request by abustany**

### CODE REVIEW

**Comment by abustany** [comment]
[clabot:check]

**Comment by abustany** [comment]
[clabot:check]

**Comment by abustany** [comment]
I'm not sure how to add a test for this... Testing all features will ensure that the `tls` feature does not break http, but do we have an easy to spin up an actual https server? It looks like jsonrpc-http-server has no helpers for that.

**Comment by tomusdrw** [comment]
@abustany can you add a job to the CI to check that the client compiles with that feature enabled?

**Comment by abustany** [comment]
Added using the build matrix feature from Travis, let me know if you'd prefer using the build script directly instead. I thought using the build matrix would lead to clearer reporting...

**Comment by abustany** [comment]
oh hmmm I just realized the build probably now publishes the documentation twice :-/

**Comment by abustany** [comment]
The fix I pushed is a bit ad-hoc... I don't know if there's a more generic way to implement it.

**Comment by tomusdrw** [comment]
Thanks!

**Pull request merged**
