### PR TITLE
Associated types in RPC traits

### PR DESCRIPTION
**Pull request by gavofyork**

### CODE REVIEW

**Comment by rphmeier** [comment]
The `ASSOCIATED` type is strange to me. For the use-cases where I need this, it would be better with regular generics.

**Comment by rphmeier** [comment]
I think by swapping the rules for traits with metadata and those without, we can get rid of the `ASSOCIATED` keyword in this.

**Comment by tomusdrw** [comment]
@gavofyork @rphmeier I believe it's not required any more in Polkadot, is it? Would be awesome to avoid `ASSOCIATED` keyword if possible, see https://github.com/paritytech/jsonrpc/pull/267#issuecomment-394734135

**Comment by rphmeier** [comment]
@tomusdrw no, not needed for polkadot any more. 100% agree about ASSOCIATED keyword.

**Comment by tomusdrw** [comment]
Closing, since I doesn't seem to be needed. We might consider this as part of #66

**Pull request closed without merging**
