### PR TITLE
Add client transport features

### LINKED ISSUE #431: Add features for client transports
e.g. `ws` `http`. This way we will not include dependencies that are not required.

rel: https://github.com/paritytech/jsonrpc/pull/420#discussion_r285470134

### PR DESCRIPTION
**Pull request by ascjones**
Resolves #431.

I've changed the CI script to run `core-client` build for the new features with `--manifest-path=core-client/Cargo.toml` since the features don't work with the top level cargo workspace.

### CODE REVIEW

**Comment by dvdplm** [comment]
> the features don't work with the top level cargo workspace.

Like in general or just in this project? Seems like a footgun worth knowing about!

**Comment by tomusdrw** [comment]
> Like in general or just in this project? Seems like a footgun worth knowing about!

I think in general, the point of workspace is just to group a bunch of related projects, but a workspace crate can't really be imported or used as a library.

**Comment by ascjones** [comment]
https://github.com/rust-lang/cargo/issues/5015

**Comment by dvdplm** [comment]
Will this fix CI you reckon?

**Comment by ascjones** [comment]
Cleared the caches and reran - seemed to do the trick

**Pull request merged**
